{{- if and (not .Values.postgresql.enabled) (not .Values.externalPostgresql.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "clusterjellyfin.fullname" . }}-postgresql
  labels:
    {{- include "clusterjellyfin.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.externalPostgresql.password | b64enc | quote }}
{{- end }}
