name: ABI Compatibility Build

on:
  pull_request:

permissions: {}

jobs:
  abi-head:
    name: ABI - HEAD
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup .NET
        uses: actions/setup-dotnet@baa11fbfe1d6520db94683bd5c7a3818018e4309 # v5.1.0
        with:
          dotnet-version: '10.0.x'

      - name: Build
        run: dotnet build Jellyfin.Server -o ./out

      - name: Upload Head
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: abi-head
          retention-days: 1
          if-no-files-found: error
          path: out/

  abi-base:
    name: ABI - BASE
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ github.event.pull_request.base.sha }}

      - name: Setup .NET
        uses: actions/setup-dotnet@baa11fbfe1d6520db94683bd5c7a3818018e4309 # v5.1.0
        with:
          dotnet-version: '10.0.x'

      - name: Build
        run: dotnet build Jellyfin.Server -o ./out

      - name: Upload Base
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: abi-base
          retention-days: 1
          if-no-files-found: error
          path: out/
