name: Check Issue Template
on:
  issues:
    types:
      - opened
jobs:
  check_issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: pull in script
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          repository: jellyfin/jellyfin-triage-script
      - name: install python
        uses: actions/setup-python@39cd14951b08e74b54015e9e001cdefcf80e669f # v5.1.1
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: install python packages
        run: pip install -r main-repo-triage/requirements.txt
      - name: check and comment issue
        working-directory: ./main-repo-triage
        run: python3 single_issue_gha.py
        env:
          GH_TOKEN: ${{ secrets.JF_BOT_TOKEN }}
          GH_REPO: ${{ github.repository }}
          ISSUE: ${{ github.event.issue.number }}
